version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: edubiz
      POSTGRES_PASSWORD: edubiz
      POSTGRES_DB: edubiz
    ports:
      - '5431:5432'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "edubiz"]
      interval: 5s
      retries: 5

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
      
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: cache
      REDIS_HOST: cache
      REDIS_PORT: cache:6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081
    
  ui:
    build: D:\esa\ui\
    ports:
      - "3501:3000"
    volumes:
      - D:\esa\ui\src:/app/src
    environment:
      - WDS_SOCKET_PORT=0
    depends_on:
      - engine
    

  engine:
    build: D:\esa\backend\
    ports:
      - "3502:3500"
    volumes:
      - D:\esa\backend\:/app
    environment:
      - WDS_SOCKET_PORT=0
    depends_on:
      - db
   
   
volumes:
  postgres-db-volume:
  cache: