name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: .

    - name: Rename sample to env
      run: mv sample.env .env
   
    - name: stop and downgrade all containers with images
      run: docker compose down -v --rmi
      
    - name: Build the Docker image
      run: docker compose build --no-cache

    - name: run docker compose file
      run: docker compose up -d
